service: sfFoodTruckService
provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-west-2
  environment: 
    GOOGLE_MAPS_APIKEY: ${file(./.config.dev.json):dev.GOOGLE_MAPS_APIKEY}
functions:
  getSFFoodTrucks:
    handler: handler.getSFFoodTrucks
    events:
    - http:
        path: /sfFoodTrucks
        method: post
        cors: true
